## Kubernetes cluster instance using "standard-cluster" resource class
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: demo-gke-cluster
  namespace: crossplane-system
  labels:
    provider: gcp
spec:
  classReference:
    name: standard-cluster
    namespace: crossplane-system
