---
## Kubernetes cluster instance using "standard-cluster" resource class
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: demo-cluster
  namespace: crossplane-system
  labels:
    provider: azure
spec:
  classReference:
    name: standard-cluster
    namespace: crossplane-system
  clusterVersion: "1.12"