---
# Azure Admin service principal secret - used by Azure Provider
apiVersion: v1
kind: Secret
metadata:
  name: azure-provider-creds
  namespace: crossplane-system
type: Opaque
data:
  credentials: BASE64ENCODED_AZURE_PROVIDER_CREDS
---
# Azure Provider with service principal secret reference - used to provision resources
apiVersion: azure.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: azure-provider
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    name: azure-provider-creds
    key: credentials
---
# ResourceClass that defines the blueprint for how a "standard" Azure AKS cluster
# should be dynamically provisioned
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard-cluster
  namespace: crossplane-system
parameters:
  resourceGroupName: group-westus-1
  location: Central US
  version: "1.12.8"
  nodeCount: "1"
  nodeVMSize: Standard_B2s
  dnsNamePrefix: crossplane-aks
  disableRBAC: "false"
provisioner: akscluster.compute.azure.crossplane.io/v1alpha1
providerRef:
  name: azure-provider
reclaimPolicy: Delete
---
# ResourceClass that defines the blueprint for how a "standard" Azure MySQL Server
# should be dynamically provisioned
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard-mysql
  namespace: crossplane-system
parameters:
  adminLoginName: myadmin
  resourceGroupName: group-westus-1
  location: Central US
  sslEnforced: "false"
  tier: Basic
  vcores: "2"
  family: Gen5
  storageGB: "25"
  backupRetentionDays: "7"
  geoRedundantBackup: "false"
provisioner: mysqlserver.database.azure.crossplane.io/v1alpha1
providerRef:
  name: azure-provider
reclaimPolicy: Delete

