apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: demo-cluster
  namespace: crossplane-system
  labels:
    provider: aws
spec:
  classReference:
    name: standard-cluster
    namespace: crossplane-system
  classRef:
    name: standard-cluster
    namespace: crossplane-system    
  